# default configuration
baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "K8Spin | Add multi-tenant capabilities to your Kubernetes Platform"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
URL = "plugins/slick/slick.css"

[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"

[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "oss-projects"
name = "OSS Projects"
weight = 2

# default parameters
[params]
home = "Home"
logo = "images/output-onlinepngtools.png"
# theme color
theme_color = "#000000"
# contact info
phone = "+880 2544 658 256"
address = "Based in Spain, working everywhere"
# meta description
author = "K8Spin"
description = "K8Spin team"
# google analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyrighht &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"


# contact
[params.contact]
enable = true
form_action = "https://formspree.io/xyybgppy" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
URL = "https://github.com/k8spin"
icon = "ti-github"

[[params.social]]
URL = "https://twitter.com/k8spin"
icon = "ti-twitter"

[[params.email]]
name = "Angel"
dir = "angel@k8spin.cloud"

[[params.email]]
name = "Pau"
dir = "pau@k8spin.cloud"
